### ISSUE TITLE
Using outdated get_it version

### ISSUE THREAD

**Issue by jseminck** [fzyzcjy/flutter_convenient_test#150]
**Describe the bug**
I'm pretty excited to try this out but ran into a dependency conflict:

```
Because every version of convenient_test_dev depends on get_it ^6.0.0 and my_app depends on get_it ^7.2.0, convenient_test_dev is forbidden.
```

Is there any reason you are relying on the old version or is it safe to upgrade? https://github.com/fzyzcjy/flutter_convenient_test/blob/master/packages/convenient_test_dev/pubspec.yaml#L19

**Comment by fzyzcjy** [comment]
Let me have a look

**Comment by fzyzcjy** [comment]
It is safe to upgrade :)
