### ISSUE TITLE
Windows - How to open the manager?

### ISSUE THREAD

**Issue by MalteBoehm** [fzyzcjy/flutter_convenient_test#208]
Hey there, is there a way to open it on windows without downloading your example files? 

Greetings :)

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_convenient_test/tree/master/packages/convenient_test_manager - the manager - is a very normal Flutter app. Just run it :)

**Comment by fzyzcjy** [comment]
Btw I forgot to release a new version to pub.dev which is outdated, so please use the version on master branch temporarily.

**Comment by MalteBoehm** [comment]
Hey, thanks for answering so fast! 
Im still not able to build it. Now with this error. Do you have an idea what to do with it? :)

`Building Windows application...
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.9/lib/src/widgets/controls.dart(185,55): error G76A9B1F6: The method 'back' isn't defined for the class 'Player'. [C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Der benutzerdefinierte Build f�r "C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\CMakeFiles\325b214bec33ed2f9e8714f29aed6396\flutter_windows.dll.rule;C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\CMakeFiles\b7032fb54d07fcd384d848d583fe5d8d\flutter_assemble.rule" wurde mit dem Code 1 beendet. [C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\flutter\flutter_assemble.vcxproj]
C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(68,11): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(68,11): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\api\api.cc(315,59): warning C4267: "=": Konvertierung von "size_t" nach "int32_t", Datenverlust m�glich [C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\api\api.cc(336,51): warning C4267: "=": Konvertierung von "size_t" nach "int32_t", Datenverlust m�glich [C:\Projekte\Flutter\flutter_convenient_test\packages\convenient_test_manager\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
Exception: Build process failed.
`

**Comment by fzyzcjy** [comment]
Sounds like not a problem by my package, but instead `dart_vlc`.

If really cannot compile, you may remove this dependency (and corresponding code) - but then you lose the feature of playing automatically-recorded screenshot videos.

**Comment by MalteBoehm** [comment]
About "CONVENIENT_TEST_APP_CODE_DIR=/path/to/this/app"  Which path does it mean?

**Comment by fzyzcjy** [comment]
The app you want to test. Say, I have a `MyAwesomeApp` and want to use convenient_test to test it. Then CONVENIENT_TEST_APP_CODE_DIR points to somewhere like `/Users/tom/my/projects/MyAwesomeApp` etc

**Comment by MalteBoehm** [comment]
Ah okay thank you, so its the root level of the app :)

**Comment by fzyzcjy** [comment]
Yes :)

**Comment by MalteBoehm** [comment]
I think i almost made it 🗡️ 

I/flutter (15308): 2022-05-20T15:52:02.438550Z|info|ManagerRpcService|create ciMode=false
E/flutter (15308): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 52194, details: null, rawResponse: null, trailers: {})
E/flutter (15308): 

Any idea where to play where to set it ?

**Comment by fzyzcjy** [comment]
Seems that you do not open your Manager?

**Comment by fzyzcjy** [comment]
It is possible your network is special and worker cannot connect to manager at 127.0.0.1. Then temporarily modify https://github.com/fzyzcjy/flutter_convenient_test/blob/870bbe37c0cdece06a255c34f2f3d748acef6194/packages/convenient_test_common_dart/lib/src/consts.dart#L1. (I will PR and make it configurable later)
