### ISSUE TITLE
Add `Manager` app to the github release

### ISSUE THREAD

**Issue by Maksimka101** [fzyzcjy/flutter_convenient_test#209]
**Is your feature request related to a problem? Please describe.**
It is not comfortable to clone project to run manager app.

**Describe the solution you'd like**
You can:
- add manager's source code to the release to make it easier to run it.
- add a compiled version of application for your os (mac os) as well.
- create a codemagic pipeline which will build manager for all desctop platforms and then send it somewhere.

I understand that it is not a trivial task but this enhancement will make using one of the main feature easier. Also I can try to help you with ci setup if you want :)

**Comment by fzyzcjy** [comment]
Totally agree! Indeed I have wanted to do it before: https://github.com/fzyzcjy/flutter_convenient_test/issues/50. And here is a half-finished automatic MacOS build script (though no time to finish yet): https://github.com/fzyzcjy/flutter_convenient_test/blob/870bbe37c0cdece06a255c34f2f3d748acef6194/.github/workflows/ci.yaml#L56

> Also I can try to help you with ci setup if you want :)

Looking forward to your PR! :)

**Comment by fzyzcjy** [comment]
I have done the MacOS part. https://github.com/fzyzcjy/flutter_convenient_test#method-1-download-precompiled-binary
