### ISSUE TITLE
Building Windows application... dart_vlc-0.1.9/lib/src/widgets/controls.dart(185,55): error G76A9B1F6: The method 'back' isn't defined for the class 'Player'.

### ISSUE THREAD

**Issue by MalteBoehm** [fzyzcjy/flutter_convenient_test#217]
**Describe the bug**
You cannot build the manager on windows unless dart-vlc is manually removed in the code.

**To Reproduce**
Build the Test Manager on a windows system:
Building Windows application...
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.9/lib/src/widgets/controls.dart(185,55): error G76A9B1F6: The method 'back' isn't defined for the class 'Player'. [C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Der benutzerdefinierte Build f�r "C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\CMakeFiles\e98853f581c37bfc0e218fc29ee9c627\flutter_windows.dll.rule;C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\CMakeFiles\c339ceab05c763d608fa9068abed8dc9\flutter_assemble.rule" wurde mit dem Code 1 beendet. [C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

**Desktop (please complete the following information):**
 - Windows 11 Pro

**Comment by fzyzcjy** [comment]
Hmm how does `dart-vlc` say? This is a bug of their library.

I do hope dart-vlc exists, otherwise videos (screenshot videos) cannot be displayed in windows - you lose one feature :(

**Comment by MalteBoehm** [comment]
I will find out what they will see and let you know in this issue.

If it keeps that way from their side i can commit a platform feature switch.

**Comment by fzyzcjy** [comment]
Totally agree.

**Comment by fzyzcjy** [comment]
Given that this also makes MacOS not able to build a release binary (https://github.com/fzyzcjy/flutter_convenient_test/issues/186), we may really need to make a feature switch.

It worked well before, but dnk why it does not work now.

**Comment by fzyzcjy** [comment]
* https://github.com/fzyzcjy/flutter_convenient_test/issues/219

**Comment by fzyzcjy** [comment]
I reproduced it in CI.

```
Run flutter build macos
Changing current working directory to: /Users/runner/work/flutter_convenient_test/flutter_convenient_test/packages/convenient_test_manager

💪 Building with sound null safety 💪

Running pod install...                                             25.3s
Building macOS application...                                   
../../../../../hostedtoolcache/flutter/3.0.1-stable/x64/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.9/lib/src/widgets/controls.dart:1[8](https://github.com/fzyzcjy/flutter_convenient_test/runs/6543875530?check_suite_focus=true#step:8:9)5:55: Error: The method 'back' isn't defined for the class 'Player'.
 - 'Player' is from 'package:dart_vlc_ffi/src/player.dart' ('../../../../../hostedtoolcache/flutter/3.0.1-stable/x64/.pub-cache/hosted/pub.dartlang.org/dart_vlc_ffi-0.1.7/lib/src/player.dart').
Try correcting the name to the name of an existing method, or defining a method named 'back'.
                              onPressed: () => player.back(),
                                                      ^^^^
```

will fix it.

**Comment by fzyzcjy** [comment]
according to CI, should have no problem now?

feel free to reopen if it still exists

**Comment by MalteBoehm** [comment]
> 

It throws some errors while building, but it works! 

While running one test:
```dart
void main() {
  convenientTestMain(MyConvenientTestSlot(), () {
    group('Login Test', () {
      tTestWidgets('Expect to be on Sign In View', (t) async {
        assert(find.text("Sign In") == true);
      });
    });
  });
}```

it throws:
'package:flutter_test/src/binding.dart': Failed assertion: line 802 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.
dart:core-patch/errors_patch.dart 51:61       _AssertionError._doThrowNew
dart:core-patch/errors_patch.dart 40:5        _AssertionError._throwNew
package:flutter_test/src/binding.dart 802:14  TestWidgetsFlutterBinding._runTest.handleUncaughtError
package:flutter_test/src/binding.dart 807:9   TestWidgetsFlutterBinding._runTest.<fn>
dart:async/zone.dart 1109:14                  _Zone._processUncaughtError
dart:async/zone.dart 1312:5                   _CustomZone.handleUncaughtError
dart:async/future_impl.dart 716:16            Future._propagateToListeners
dart:async/future_impl.dart 574:5             Future._completeError
dart:async-patch/async_patch.dart 287:13      _completeOnAsyncError
package:flutter_test/src/binding.dart         TestWidgetsFlutterBinding._runTestBody


And you probably need to expand one widget in the top right corner :)
![image](https://user-images.githubusercontent.com/71656205/169701981-10b19506-34cc-4e3c-a548-9ad2c717788c.png)

**Comment by MalteBoehm** [comment]
![image](https://user-images.githubusercontent.com/71656205/169703671-e9de34dc-a258-4862-8456-6e37a4c87013.png)

Looks great, but as far I can tell, clicking on the video gets ignored. I started a couple of times and sometimes i can see a video.

**Comment by fzyzcjy** [comment]
> And you probably need to expand one widget in the top right corner :)

See latest version, I expanded the screen size

**Comment by fzyzcjy** [comment]
> it throws:

Could you please create a new issue, with *all* logs from the worker?
I guess there are some other errors.

**Comment by fzyzcjy** [comment]
> Looks great, but as far I can tell, clicking on the video gets ignored. I started a couple of times and sometimes i can see a video.

Probably because your test is too short? Start/stop recording a video takes some time, and if tests too short it will record nothing.
