### ISSUE TITLE
How to select on widget when more than one are find ?

### ISSUE THREAD

**Issue by Bazni** [fzyzcjy/flutter_convenient_test#230]
Hi,
First, thank you for your work. Its exactly the package I want to start testing apps.

I use `find.text` method to find my widget but on my page I have several widget with the same text but some are not visible. 

`await find.text('Champ obligatoire').should(isSameColorAs(AppColors.red));`

Is it possible to select one from the list I get from the code above or do I need to use `find.byKey` to be specific on a widget ? 
If I use `find.byKey` can I check if my widget is visible ?

Thx you again for your work

**Comment by Bazni** [comment]
Thx for your reply. 

With `.should(isSameColorAs(AppColors.red))` I get this :
```
Expected: matches color Color(0xffce2d2d)
  Actual: _TextFinder:<2 widgets with text "Champ obligatoire" (ignoring offstage widgets): [
  Text("Champ obligatoire", debugLabel: (((englishLike bodySmall 2014).merge(((blackCupertino bodySmall).apply).merge(blackCupertino bodySmall))).copyWith).merge(unknown), inherit: false, color: Color(0x00000000), family: .SF UI Text, size: 0.0, weight: 400, baseline: alphabetic, height: 0.0x, decoration: TextDecoration.none, textAlign: start, overflow: ellipsis, dependencies: [MediaQuery, DefaultTextStyle]), 
  Text("Champ obligatoire", inherit: true, color: Color(0xffce2d2d), family: Regular, size: 12.0, dependencies: [MediaQuery, DefaultTextStyle])
  ]>
```
I don't know from where the first one came from (I test a code from another dev) but is there a way to only select the 2nd with `.should` ? Like using `.should` in a row to be more specific (maybe later ?).

**Comment by MalteBoehm** [comment]
If u still got provlems i think there are test ids too you can give to widgets

**Comment by Bazni** [comment]
Thank you for your response, I manage to do what I want with your help.

**Comment by fzyzcjy** [comment]
🎉
