### ISSUE TITLE
Add one liner documentation how to actually use CI mode

### ISSUE THREAD

**Issue by janknips** [fzyzcjy/flutter_convenient_test#240]
I can't figure out how to use it, because there used to be a flag for it, which is now gone, and the entire project contains no mention of the word CI anymore :D

**Comment by fzyzcjy** [comment]
You are right, I forgot to update the doc...

**Comment by fzyzcjy** [comment]
This is how I personally use it:

```
dart run convenient_test_manager_dart # in one shell
flutter run path/to/your/integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=sth # in another shell, run your worker app

**Comment by janknips** [comment]
But will it terminate like that? Seems like this is what I'm already doing locally 😁 So for CI I would need a mode that terminates after all tests ran

**Comment by fzyzcjy** [comment]
Yes it terminates automatically after all tests run.

**Comment by jangruenwaldt** [comment]
Okay, does it require the manager to be run? For a lighter CI script some people probably don't need that

**Comment by janknips** [comment]
> This is how I personally use it:
> 
> ```
> dart run convenient_test_manager_dart # in one shell
> flutter run path/to/your/integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=sth # in another shell, run your worker app
> ```

Could not find file `convenient_test_manager` 😛  Which directory are you running in / which build command did you run before this?

**Comment by fzyzcjy** [comment]
> Could not find file convenient_test_manager

https://github.com/fzyzcjy/flutter_convenient_test/tree/master/packages/convenient_test_manager_dart

**Comment by fzyzcjy** [comment]
> Lost connection to device.

Strongly suspect it is because: https://github.com/fzyzcjy/flutter_convenient_test/issues/188

And it is fixed: https://github.com/flutter/engine/pull/34496

**Comment by janknips** [comment]
> > Lost connection to device.
> 
> Strongly suspect it is because: #188. See that issue for a lot of details.
> 
> It is discussed in: [flutter/flutter#37818](https://github.com/flutter/flutter/issues/37818)
> 
> And it is fixed: [flutter/engine#34496](https://github.com/flutter/engine/pull/34496), but not landed in stable.

I see, thanks 👍  I will try again with master branch and let you know. Let's hope for a either hotfix or fast next update 😅

**Comment by fzyzcjy** [comment]
> Unfortunately, it seems quite unreliable, e.g. worker disconnects, etc, at least I never got my tests to pass, which usually easily pass.

If the *only* problem is "lost connection to device" maybe it is #188 problem; if many other problems feel free to create separate issues

**Comment by fzyzcjy** [comment]
> I see, thanks 👍 I will try again with master branch and let you know. Let's hope for a either hotfix or fast next update 😅

Yes personally I also suffer from this problem :( So eagerly looking forward to next stable!

**Comment by janknips** [comment]
> > Unfortunately, it seems quite unreliable, e.g. worker disconnects, etc, at least I never got my tests to pass, which usually easily pass.
> 
> If the _only_ problem is "lost connection to device" maybe it is #188 problem; if many other problems feel free to create separate issues

Thanks, yeah for now I can't really tell if anything else is broken 😄 will let you know if I find any other issues!

**Comment by fzyzcjy** [comment]
> Maybe it would be good to add another barebone CI mode that will just detect wether flutter test was used, and in that case, just work as if only integration_test was used, without using the manager. What do you think? At least in my use case I can imagine just calling this in CI, since it's fast, and failed tests could still be re-run locally afterwards.

Some features will be lost (e.g. "isolation mode", "all screenshots and videos", etc). But I guess it is implement-able. Feel free to PR!

**Comment by fzyzcjy** [comment]
> Thanks, yeah for now I can't really tell if anything else is broken 😄 will let you know if I find any other issues!

Sure, take your time! I personally feel it stable except for that problem; for my own case it is sometimes also not stable because I did e2e tests with a backend and docker etc which is source of unstableness - but that is surely not your case and not related to this package
