### ISSUE TITLE
Feature: flag to skip `pumpAndSettle` when calling `TFinderCommand.act`

### ISSUE THREAD

**Issue by MCord** [fzyzcjy/flutter_convenient_test#249]
**Is your feature request related to a problem? Please describe.**
When a widget contains a looping animation, `pumpAndSettle` never finishes and the `act` method blocks the test.

**Describe the solution you'd like**
I would like an optional flag on the `TFinderCommand.act` that allows to call `pump` instead of `pumpAndSettle`.

**Describe alternatives you've considered**
At this moment I am not aware of any solution to make the test pass short of removing the looping animation.

**Additional context**

I would be more than happy to send a PR if the proposed solution is pertinent.

**Comment by fzyzcjy** [comment]
Good idea! Feel free to PR :)
