### ISSUE TITLE
Junit Test Report for Circle CI Compatibility 

### ISSUE THREAD

**Issue by ethancadoo** [fzyzcjy/flutter_convenient_test#261]
**Is your feature request related to a problem? Please describe.**

I want to be able to display my test results with circle ci but the results need to be in junit format.

**Describe the solution you'd like**

In other testing frameworks, such as jest in nodejs there are "test-reporters" that can export results in a particular format. https://www.npmjs.com/package/jest-junit

I think adding the option to spit out the results with a command line arg would be awesome.

**Describe alternatives you've considered**

There really isn't an alternative for circle ci.

**Additional context**

I am not concerned if *all* the information is converted into the junit report (such as stack trace, vars... etc). I really just want the name of each test that passed and which failed.

**Comment by fzyzcjy** [comment]
Good idea!

> I am not concerned if all the information is converted into the junit report (such as stack trace, vars... etc). I really just want the name of each test that passed and which failed.

That should not be quite hard IMHO.
