### ISSUE TITLE
Firebase Test Lab Compatibility 

### ISSUE THREAD

**Issue by ethancadoo** [fzyzcjy/flutter_convenient_test#262]
**Is your feature request related to a problem? Please describe.**

I would really like to make use of firebase test lab in order to quickly test both an IOS and Android app. However Firebase Test Lab requires that your integration tests are bundled within an apk and that they are self executing. https://github.com/flutter/flutter/tree/main/packages/integration_test#android-device-testing

Given those constraints, I do not think there is a way to have the manager drive the tests.  

**Describe the solution you'd like**

I would like there to be an option that could be passed in that would allow the tests to run automatically, without any intervention from the manager application.

**Describe alternatives you've considered**

The only alternative is to run our integration tests within an android emulator or IOS simulator. We can not test on real devices using this package.

**Additional context**

**Comment by fzyzcjy** [comment]
> allow the tests to run automatically, without any intervention from the manager application.

That is possible if you do not use some of the features such as "isolated tests" (which requires a lot of hot restart).

A rough thought: We can "embed" the manager_dart into the worker. Not really embed a command line binary, but just combine some code into it.

> We can not test on real devices using this package.

Btw seems firebase test lab is quite expensive IIRC?

I personally plug in my own phone into my computer and run the tests on it. It works well for me.

**Comment by Halimeh-manaf** [comment]
> > @Halimeh-manaf I'm also wondering if we can use it with firebase test lab.
> 
> In addition to the ideas above, I come up with a new thought just now:
> 
> Maybe we can migrate the `manager` onto a phone as well. You know, the manager is written in flutter so it should be mainly runnable on phones. Then, since our manager and worker are both run on phone, there is no dependency on a desktop anymore, and firebase should be happy.

This would really nice!

**Comment by fzyzcjy** [comment]
@Halimeh-manaf Feel free to PR and I am looking forward to it :)
