### ISSUE TITLE
Error: Type 'WorkerModeIntegrationTest' not found.

### ISSUE THREAD

**Issue by ChristianConstantNel** [fzyzcjy/flutter_convenient_test#270]
**Describe the bug**
When running the following command: 
flutter run /path/to/your/app/integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=/path/to/this/app
I get this error along many others,
Error: Type 'WorkerModeIntegrationTest' not found.

**To Reproduce**
Run flutter run /path/to/your/app/integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=/path/to/this/app

**Expected behavior**
Test should start running

**Smartphone (please complete the following information):**
 - Device: iPhone SE Simulator on Macbook M1
 - 
**Additional context**
Any help would be greatly appreciated. I've heard such good things about this package and I know it will save our team tons of time.

**Comment by fzyzcjy** [comment]
Try to use the latest version, i.e. the master branch

**Comment by ChristianConstantNel** [comment]
Of the package?
I'll give it a go!

**Comment by ChristianConstantNel** [comment]
So I've added this to my normal dependencies:
convenient_test:
    git: 
     url: https://github.com/fzyzcjy/flutter_convenient_test.git
     path: packages/convenient_test

And this to my dev dependencies 
convenient_test_dev:
    git: 
     url: https://github.com/fzyzcjy/flutter_convenient_test.git
     path: packages/convenient_test_dev

But I get this error:
Because every version of convenient_test_dev from git depends on convenient_test from hosted and fan depends on convenient_test from git, convenient_test_dev from git is forbidden.
So, because fan depends on convenient_test_dev from git, version solving failed.

Any ideas?

Really appreciate the help.

**Comment by fzyzcjy** [comment]
dependency_overrieds

**Comment by ChristianConstantNel** [comment]
Like so?

dependency_overrides:
    convenient_test: ^1.1.1

**Comment by fzyzcjy** [comment]
Check its doc :)

**Comment by ChristianConstantNel** [comment]
I've tried this,

 dependency_overrides:
    convenient_test: '1.1.1'
    convenient_test_dev: '1.1.1'

But that's also not working, should I download the package locally and specify the path in the dependency_overrides?

**Comment by ChristianConstantNel** [comment]
Nice!! Got it running. 
Thank you so much!

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by ChristianConstantNel** [comment]
Just got everything running and wow man! This really is such a great tool.
Thank you for sharing it!

**Comment by fzyzcjy** [comment]
😄 Happy to hear that and you are welcome!

**Comment by bartekpacia** [comment]
I think this can be closed :)
