### ISSUE TITLE
Running tests on an app with an infinitely repeating animation causes `tTestWidgets` to timeout.

### ISSUE THREAD

**Issue by ronba** [fzyzcjy/flutter_convenient_test#272]
**Describe the bug**
Running tests on an app with an infinitely repeating animation causes `tTestWidgets` to timeout before ever executing the test.
The root cause is the usage of pumpAndSettle inside tTestWidgets before starting the app.  

**To Reproduce**
Repro code with comments is included below.  Component explanation:
- `DemoHome` - a simple stateful widget which runs an infinitely repeating animation (forward -> reverse -> forward ...)
- `pumpUntilFound` - extension method on ConvenientTest that continuously pumps until a widget of a specific Type appears on the screen.
- `wTestWidgets` - my workaround based on `tTestWidgets`: a custom test method using `pumpUntilFound`.
- `main()` - starts the integration tests, contains two tests which run DemoHome. 
  - The first test uses `wTestWidgets` and will pass.
  - The second uses `tTestWidgets` and will timeout.

**Expected behavior**
The package should support the scenario of testing an app with an infinite animation.

**Questions**
Am I missing some functionality? Is the approach to the test wrong?

Otherwise, I think something like `wTestWidgets` provides a reasonable solution for the problem above.  
I'm happy to send a PR:

Option 1: Split into 2 different methods.
- Similar to what I have in the code.
- Add documentation to tTestWidgets along the lines of "if your test never starts use wTestWidgets."
- Make the timeout for pumpAndSettle significantly shorter by default and also customizable (maybe 5-10 seconds). 
  When a test times out - catch it and add a meaningful error before rethrowing.
- waitFor would be of type Finder instead of Type. 

Option 2: Make tTestWidgets smarter.
- Accept an optional finder argument and a timeout.
  - If a finder is specified - use `pumpUntilFound` with the timeout.
  - Otherwise - use pumpAndSettle with the timeout.
- Make the timeout for pumpAndSettle significantly shorter by default and also customizable (maybe 5-10 seconds). 
  When a test times out - catch it and add a meaningful error before rethrowing.

Or... something else?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 13.0

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android
 - Version: 12

**Additional context**

Code:
```dart
import 'package:convenient_test/convenient_test.dart';
import 'package:convenient_test_dev/convenient_test_dev.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:meta/meta.dart';

void main() {
  convenientTestMain(_DemoHomeTestSlot(), () {
    group('simple test group', () {
      wTestWidgets(
        'This will wait for the DemoHome widget to become visible '
        'and then complete successfully.',
        waitFor: DemoHome,
        (t) async {
          expect(true, true);
        },
      );

      tTestWidgets(
        'This will wait for 10 minutes on the "START APP" stage '
        'and then timeout. The expect will never run.',
        (t) async {
          expect(true, true);
        },
      );
    });
  });
}

@isTest
void wTestWidgets(
  // ... forward the arguments ...
  String description,
  TWidgetTesterCallback callback, {
  bool skip = false,
  Type? waitFor,
}) {
  testWidgets(
    description,
    (tester) async {
      return ConvenientTest.withActiveInstance(tester, (t) async {
        final log = t.log('START APP', '');
        await _DemoHomeTestSlot().appMain(AppMainExecuteMode.integrationTest);

        if (waitFor != null) {
          await t.pumpUntilFound(find.byType(waitFor));
        } else {
          await t.pumpAndSettle();
        }
        await log.snapshot(name: 'after');
        await callback(t);
        debugDefaultTargetPlatformOverride = null;
      });
    },
    skip: skip,
  );
}

class DemoHome extends StatefulWidget {
  const DemoHome({super.key});

  @override
  State<DemoHome> createState() => _DemoHomeState();
}

class _DemoHomeState extends State<DemoHome>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      builder: (context, child) => const ColoredBox(
        color: Colors.blue,
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 300),
    )
      ..forward()
      ..addStatusListener((status) {
        if (status == AnimationStatus.completed) {
          _controller.reverse();
        } else if (status == AnimationStatus.dismissed) {
          _controller.forward();
        }
      });
  }
}

class _DemoHomeTestSlot extends ConvenientTestSlot {
  @override
  Future<void> appMain(AppMainExecuteMode mode) async => runApp(
        const MaterialApp(
          home: ConvenientTestWrapperWidget(child: DemoHome()),
        ),
      );

  @override
  BuildContext? getNavContext(ConvenientTest t) => throw UnimplementedError();
}

extension ConvenientTestX on ConvenientTest {
  // Borrowed from: https://github.com/flutter/flutter/issues/73355
  Future<void> pumpUntilFound(
    Finder finder, {
    int iterations = 200,
  }) async {
    final iterationsLength = iterations.toString().length;
    for (var i = 1; i <= iterations; i++) {
      // Useful to know if this is why tests are blocked.
      // ignore: avoid_print
      print(
        '[${i.toString().padLeft(iterationsLength, '0')}/$iterations] '
        'Waiting for ${finder.description} to be found.',
      );

      final found = tester.any(finder);
      if (found) {
        return;
      }

      await pump(const Duration(milliseconds: 100));
    }
  }
}
```

**Comment by fzyzcjy** [comment]
The title remind me of: https://github.com/fzyzcjy/flutter_convenient_test/pull/252

**Comment by ronba** [comment]
Thanks for the quick response!!
#252 solves the issue when calling act after the test has already started.  
Does it also help address the case where the first widget loaded via main in the app never settles?

From what I can tell from [tTestWidgets](https://github.com/fzyzcjy/flutter_convenient_test/blob/23a6a1c6c709357d74270e379f78d0c993d6beec/packages/convenient_test_dev/lib/src/functions/core.dart#L164) it's not possible to avoid calling pumpAndSettle?

**Comment by fzyzcjy** [comment]
You are welcome!

I guess you are right, we should be more flexible about https://github.com/fzyzcjy/flutter_convenient_test/blob/23a6a1c6c709357d74270e379f78d0c993d6beec/packages/convenient_test_dev/lib/src/functions/core.dart#L175, instead of blindly calling pump *and settle*.

The simplest solution may be add that "settle" flag just like #252 and its later PR. A more complex solution may be the ones you proposed :)
