### ISSUE TITLE
Please publish convenient_test_manager_dart binaries with a release

### ISSUE THREAD

**Issue by vHanda** [fzyzcjy/flutter_convenient_test#275]
Hi. I noticed you made a new release.

Would it be possible for you to attach the latest build of convenient_test_manager_dart (linux build) from CI to the release? This way, it'll be easier to fetch the latest version, instead of getting it via the CI.

I'd be happy to add any extra kind of automation which would make this easier.

**Comment by fzyzcjy** [comment]
Sure, looking forward to your PR!

P.S. https://github.com/fzyzcjy/flutter_rust_bridge already does so, done by @Desdaemon

**Comment by vHanda** [comment]
Bump. I haven't gotten around to it. But I will

**Comment by fzyzcjy** [comment]
Take your time!

**Comment by vHanda** [comment]
Closing this as I still haven't gotten the time, and until I get my next Flutter Client. If I'd gotten the tests running in the CI, I could have probably justified the time to keep working on them, as they would have been delivering value, and then I could have justified the extra time to improve the tooling. Sadly, I never got this to work on the CI.


My rough plan was/is -
1. Run a fake X server in docker, and also run a vnc server in the same container with a screen size of your liking - DONE
2. Find an easy way to record the vncserver - DONE - https://github.com/saily/vnc-recorder
3. Run convenient_test_manager_dart for the end2end tests inside a docker container with a Linux version of the mobile app. I mostly develop on Linux and have the app running on Linux, even though this is only supposed to be a mobile app.
4. Find a way to orchestrate all of this, + save the videos as CI artifacts for all the supported screen sizes.

This way I could cheaply run the end to end tests on GitHub Actions and have video recording of all the 

Hopefully, I'll get to find the time to do this with my next client. But I'm not actively looking for another one, so lets see when that happens.
