### ISSUE TITLE
convenient_test_manager macos for Apple silicon

### ISSUE THREAD

**Issue by sahibul-nf** [fzyzcjy/flutter_convenient_test#303]
The macos manager application that is in CI can't run on my mac device that uses an Apple silicon chip
because after I checked, it turns out that the macOS manager application is an application with Intel support

**Comment by fzyzcjy** [comment]
Feel free to create a PR to .github/ci.yaml!

Or, download code and package the app by yourself

**Comment by sahibul-nf** [comment]
after I downloaded the code and built the macOS application with the "flutter build macos" command, I got an error like this

`flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Intermediates.noindex/Pods.build/Debug/dart_vlc.build/Script-32C2552F11E9070B254CC3EBBA17EC72.sh: line 2: cmake: command not found
Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase '[CP-User] Fetch submodules... only needed if using git in pubspec.yaml' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'dart_vlc' from project 'Pods')
warning: Run script build phase '[CP-User] Build common lib' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'dart_vlc' from project 'Pods')
warning: Run script build phase '[CP-User] Change VLCKit ID' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'dart_vlc' from project 'Pods')
** BUILD FAILED **`

is there anything i have to do first to setup or what?

**Comment by fzyzcjy** [comment]
Hmm looks like dart_vlc problem, maybe file a issue there

**Comment by sahibul-nf** [comment]
I have fixed it. After many things I did, I had to upgrade the dependency dart_vlc to dart_vlc: ^0.3.0

but so far I'm getting an application with a blank display like this image. Is there something I'm missing?

![Image](https://cdn.loom.com/images/originals/608fbdf170a1410ba49bfb932d6a4642.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4ubG9vbS5jb20vaW1hZ2VzL29yaWdpbmFscy82MDhmYmRmMTcwYTE0MTBiYTQ5YmZiOTMyZDZhNDY0Mi5qcGciLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzExNTYxNDR9fX1dfQ__&Key-Pair-Id=APKAJQIC5BGSW7XXK7FQ&Signature=noDkswjIZa7%7EA3fc0qYfApCm2PY03i2vZ26UB4-sc6a60oiLMC9y5CbhHQQ%7EhDGha7hGe2sTAQQALt-NvDOSWrbHVt87285DGZkDX-qzVB0G7krVTruO1e4FrlQNwyLoa1CExzq2R1aNsN-P-WeTEZXxZwSdln8q5RjvrJs0eZj%7ETLRmyk2ABQQK-Vud8MAkApO5cHXuIjNy%7EF4jP9krgiDVf7M38NHdcrcsEuXtPjeTJaIXV83PkZSHfir0WOu5GmPTBrHltPvnFebPqIztd6Pl%7EjkDv-Im-SZArGNCYnqZ6f6kdygx-CoSrv3VayDxcboGRSnrC1ojYo3VChxOfg__)


I run test my app with this command
```bash
flutter run /Users/sahibul/Documents/acehnese_dictionary/integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=/Users/sahibul/Desktop/convenient_test_manager.app
```

then run the convenient_test_manager application

**Comment by fzyzcjy** [comment]
Hmm please provide logs of the manager as well as worker

**Comment by sahibul-nf** [comment]
```bash
Launching integration_test/main_test.dart on iPhone 14 Pro in debug mode...
Running pod install...                                           1,118ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.4s
Xcode build done.                                           13.8s
flutter: 2022-12-15T02:27:30.395186Z|debug|ConfigureGoldens|configure autoUpdateGoldenFiles=false comparator.basedir=file:///Users/sahibul/Desktop/convenient_test_manager.app/integration_test/
flutter: 00:00 +0: Test no logged in user scenario Search word and see detail of word on detail page
flutter: 00:00 +0 ~1: (tearDownAll)
flutter: Warning: integration_test plugin was not detected.
flutter:
flutter: If you're running the tests with `flutter drive`, please make sure your tests
flutter: are in the `integration_test/` directory of your package and use
flutter: `flutter test $path_to_test` to run it instead.
flutter:
flutter: If you're running the tests with Android instrumentation or XCTest, this means
flutter: that you are not capturing test results properly! See the following link for
flutter: how to set up the integration_test plugin:
flutter:
flutter: https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
flutter:
flutter: 2022-12-15T02:27:30.500967Z|warn|ConvenientTestMain|ConvenientTest captured error (via runZonedGuarded). type(e)=GrpcError exception=gRPC Error (code: 2, codeName: UNKNOWN, message: Null check operator used on a null value, details: [], rawResponse: null, trailers: {}) stackTrace=
flutter: 2022-12-15T02:27:30.501809Z|warn|ConvenientTestMain|ConvenientTest captured error (via runZonedGuarded). type(e)=GrpcError exception=gRPC Error (code: 2, codeName: UNKNOWN, message: Null check operator used on a null value, details: [], rawResponse: null, trailers: {}) stackTrace=
flutter: 00:00 +1 ~1: All tests passed!
Syncing files to device iPhone 14 Pro...                           250ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 14 Pro is available at: http://127.0.0.1:9753/
The Flutter DevTools debugger and profiler on iPhone 14 Pro is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:9753/
```

**Comment by sahibul-nf** [comment]
this log of the manager

```bash
Performing hot restart...                                               
Restarted application in 834ms.
flutter: 2022-12-15T02:35:50.071707Z|debug|GlobalConfigNullable|parseConfigFile homeDirectory=/Users/sahibul
flutter: 2022-12-15T02:35:50.091319Z|debug|GlobalConfigNullable|parseConfigFile configFilePath=/Users/sahibul/.config/convenient_test.json
flutter: 2022-12-15T02:35:50.116782Z|debug|GlobalConfigNullable|parse call parseConfigFile config=GlobalConfigNullable(isolationMode: null, enableReportSaver: null, goldenDiffGitRepo: null)
flutter: 2022-12-15T02:35:50.117930Z|debug|GlobalConfigNullable|parse call parseEnvironment config=GlobalConfigNullable(isolationMode: null, enableReportSaver: null, goldenDiffGitRepo: null)
flutter: 2022-12-15T02:35:50.189347Z|info|VmServiceWrapperService|Connecting to vm service at ws://127.0.0.1:9753/ws. Please ensure your Flutter app has port=9753
flutter: 2022-12-15T02:35:50.242077Z|info|setup|GlobalConfig: isolationMode: false,[NL]enableReportSaver: false,[NL]goldenDiffGitRepo: null[NL]    
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc': dlopen(/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc, 0x0001): tried: '/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/Library/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/System/Library/Frameworks/dart_vlc.framework/dart_vlc' (no such file, not in dyld cache)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      DartVLC.initialize (package:dart_vlc_ffi/src/internal/initializer.dart:19:39)
#3      DartVLC.initialize (package:dart_vlc/dart_vlc.dart:140:19)
#4      setup (package:convenient_test_manager/misc/setup.dart:28:17)
<asynchronous suspension>
#5      main (package:convenient_test_manager/main.dart:7:3)
<asynchronous suspension>

flutter: 2022-12-15T02:35:50.422140Z|info|_ServiceConnectionManager|vmServiceOpened
flutter: 2022-12-15T02:35:50.491148Z|info|_ServiceConnectionManager|handleServiceEvent kind=ServiceRegistered service=reloadSources method=s0.reloadSources
flutter: 2022-12-15T02:35:50.500707Z|info|_ServiceConnectionManager|handleServiceEvent kind=ServiceRegistered service=hotRestart method=s0.hotRestart
flutter: 2022-12-15T02:35:50.502264Z|info|_ServiceConnectionManager|handleServiceEvent kind=ServiceRegistered service=flutterVersion method=s0.flutterVersion
flutter: 2022-12-15T02:35:50.502430Z|info|_ServiceConnectionManager|handleServiceEvent kind=ServiceRegistered service=compileExpression method=s0.compileExpression
flutter: 2022-12-15T02:35:50.502551Z|info|_ServiceConnectionManager|handleServiceEvent kind=ServiceRegistered service=flutterMemoryInfo method=s0.flutterMemoryInfo
flutter: 2022-12-15T02:35:50.502648Z|info|_ServiceConnectionManager|handleServiceEvent kind=ServiceRegistered service=flutterGetSkSL method=s0.flutterGetSkSL
```

**Comment by fzyzcjy** [comment]
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc': dlopen(/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc, 0x0001): tried: '/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/Users/sahibul/Documents/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/Library/Frameworks/dart_vlc.framework/dart_vlc' (no such file), '/System/Library/Frameworks/dart_vlc.framework/dart_vlc' (no such file, not in dyld cache)

Looks like dart_vlc is still not loaded

**Comment by sahibul-nf** [comment]
do you have a solution to fix that?

**Comment by fzyzcjy** [comment]
that's dart_vlc's problem, not convenient_test's. Anyway, you may disable the dependency as well

**Comment by sahibul-nf** [comment]
Ok bro, thank you

**Comment by fzyzcjy** [comment]
You are welcome!
