### ISSUE TITLE
Dark mode for Manager

### ISSUE THREAD

**Issue by gilice** [fzyzcjy/flutter_convenient_test#318]
**Is your feature request related to a problem? Please describe.**
My eyes are burning out when working with tests during nighttime

**Describe the solution you'd like**
- convenient-test-manager to have a dark mode switch. I
- It isn't that hard to implement, basically just pass `ThemeMode: ThemeMode.system` to the MaterialApp() instance and flutter will do the rest.
- Currently the background of scaffolds is force-set to white, we should remove that. 
  - Why is that there in the first place? https://github.com/fzyzcjy/flutter_convenient_test/blob/12e774f1ba40410ccec74275b908956780aa74ca/packages/convenient_test_manager/lib/main.dart#LL18C6-L19C10

**Additional context**
# 🌃 💻️💡    👀👤    ➡️➡️     😵

**Comment by fzyzcjy** [comment]
Looks reasonable, feel free to PR!
