### ISSUE TITLE
Forcing window size leads to being unusable on small screens

### ISSUE THREAD

**Issue by gilice** [fzyzcjy/flutter_convenient_test#321]
**To Reproduce**
1. Open manager on a small screen
2. Explore behavior like this:
![picture of convenient_test_manager being messed up](https://user-images.githubusercontent.com/104317939/219634455-3d972b32-e625-45f6-b34e-7008133dbf09.png)

**Expected behavior**
Flutter has out of the box support for resizing content based on screen size
(like with Wrappers, etc). The app adapts to the smaller screen size.

**Additional context**
This happens because of this:
https://github.com/fzyzcjy/flutter_convenient_test/blob/12e774f1ba40410ccec74275b908956780aa74ca/packages/convenient_test_manager/lib/misc/setup.dart#L44

**Comment by fzyzcjy** [comment]
Totally agree. Feel free to refine the UI!

**Comment by gilice** [comment]
Thanks! Will do!!!

**Comment by gilice** [comment]
Thanks for the quick replies once again.


What I am planning to do:
- rework the frontend code to be a bit clearer 
- fix responsive design
- fix hardcoded colours, etc.

while the primary goal is
**don't change the look of the UI, just the inside**
