### ISSUE TITLE
Patrol compabibility for tapping notifications, permissions, etc

### ISSUE THREAD

**Issue by neiljaywarner** [fzyzcjy/flutter_convenient_test#325]
Would it be possible to support patrol?
https://patrol.leancode.co/

**Comment by fzyzcjy** [comment]
IMHO that package also wraps the raw testing package. Thus flutter_convenient_test seems to be a package parallel to it. However, it may be interesting to merge the two in some way!

**Comment by neiljaywarner** [comment]
Patrol lets you tap permission dialog and notifications shade.

....sent from my phone

**Comment by fzyzcjy** [comment]
Totally agree. That's why I created an issue: https://github.com/leancodepl/patrol/issues/995
