### ISSUE TITLE
doc: Clarify that video recording does not support Android currently

### ISSUE THREAD

**Issue by Brendonsk** [fzyzcjy/flutter_convenient_test#339]
So I was having trouble getting video recordings to play through the manager (Only for non-passing tests, since the passing ones didn't even open the video tab when I clicked the video icon), and after enabling some logs and doing some digging, I found out that the abstract class `VideoRecorderService`, on the `convenient_test_manager_dart` package, that gets inherited to implement video recording, mentions that Android support is not yet implemented
https://github.com/fzyzcjy/flutter_convenient_test/blob/6992d0278359c39d43744e2a98b11b680f6cfebd/packages/convenient_test_manager_dart/lib/services/screen_video_recorder_service.dart#L6-L10

I'm only asking for clarification on the README of this lack of support, since I myself don't have the technical knowledge to implement such feature and make a PR, and also ain't asking it to be implemented by other mantainers

For reference, I'm running the manager with code from the most recent master (commit [#6992d02](https://github.com/fzyzcjy/flutter_convenient_test/commit/6992d0278359c39d43744e2a98b11b680f6cfebd) as of creating this issue), and am also running my test app (being run on an android 9 emulator on the same machine) with overriden dependencies from this package to pull from the latest master

**Comment by fzyzcjy** [comment]
Done in https://github.com/fzyzcjy/flutter_convenient_test/commit/c8864d023a4c3e6d72e501c92b235f94a3cef174 :)

**Comment by Brendonsk** [comment]
That was fast, thanks!

Also, can I close issues that I made which were already resolved, or would you like to do that yourself?

**Comment by fzyzcjy** [comment]
Sure, feel free to close!

**Comment by Brendonsk** [comment]
Alright
