### ISSUE TITLE
OSX Binary for 1.3.0

### ISSUE THREAD

**Issue by ahmdt** [fzyzcjy/flutter_convenient_test#343]
Hi, thank you for the new release. This package rocks.
Unfortunately the precompiled macos binary is not triggered. Can you do it manually?
Big thanks in advance!

**Comment by fzyzcjy** [comment]
Yes, I temporarily disabled it because the GitHub CI somehow fails... (though it works well locally). Feel free to PR to fix that CI!

**Comment by ahmdt** [comment]
It seems that dart_vlc is the problem. the project is discontinued in favor of https://github.com/alexmercerind/media_kit

**Comment by fzyzcjy** [comment]
I see, then maybe we can remove dart_vlc (at least temporarily). I added that in the initial release, but in this year I seldom use it - the screenshot feature is often quite enough for me. I cannot stand for how other users use this feature though.
