### ISSUE TITLE
Architecture and Design of this framework

### ISSUE THREAD

**Issue by Raghavaraju-K** [fzyzcjy/flutter_convenient_test#344]
Hi ,

Could you please let me know the detailed architecture and design you have followed for this framework?

Thanks
Raghava

**Comment by fzyzcjy** [comment]
(Previous discussion: https://github.com/fzyzcjy/flutter_convenient_test/discussions/8#discussioncomment-6672327)

**Comment by fzyzcjy** [comment]
Given that I do not have much time recently, I will briefly explain it first now:

* It has a manager (the GUI app you use on your computer) and a worker (running on android/ios simulator or real device, etc)
* Manager controls the worker
* communicate via grpc

**Comment by Raghavaraju-K** [comment]
Thank you for quick reply.Hope I will get in detail when you find some free time. by the way I am not able to extract the source code zip file. did you publish the project as readonly? Kindly suggest

**Comment by fzyzcjy** [comment]
> by the way I am not able to extract the source code zip file. did you publish the project as readonly? Kindly suggest

I am not sure where you get the zip? 

![image](https://github.com/fzyzcjy/flutter_convenient_test/assets/5236035/4ec6a3ae-4635-4c65-baf6-810f8342fb19)


this one works for me.

could you please screenshot etc to provide a bit more details

**Comment by Raghavaraju-K** [comment]
Hi,
Thank you for the reply.I have an issue when I am trying to run the build 

I am getting the below error. please suggest on the same

Failed to load "C:/Users/E008540/Downloads/sample_test/integration_test/app_test.dart": gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 42796, details: null, rawResponse: null, trailers: {})

**Comment by fzyzcjy** [comment]
Hi, could you please create a new issue? Then it is easier for further readers to search
