### ISSUE TITLE
grpc error in windows

### ISSUE THREAD

**Issue by Raghavaraju-K** [fzyzcjy/flutter_convenient_test#346]
Hi,

I am getting below error while executing the test. Do we need to install grpc locally in our system? please suggest

Failed to load "C:/Users/username/Downloads/sample_test/integration_test/app_test.dart": gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 42796, details: null, rawResponse: null, trailers: {})

**Comment by fzyzcjy** [comment]
Hi, could you please check the network problems? i.e. this is more like a general network problem than a bug in this repo. If your phone/simulator can connect to your computer, then the grpc should be ok.

**Comment by Raghavaraju-K** [comment]
sure, thanks for the reply, so do we need to install grpc in the system or this framework  will work automatically?

**Comment by fzyzcjy** [comment]
No need to install. grpc is just some source code already packaged inside.

**Comment by Raghavaraju-K** [comment]
ok,thank you very much.

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by lthoedt** [comment]
Okay turns out i missed something in the readme which explains this error. It says to look at #253 . I fixed it by changing:
```dart
const String kConvenientTestManagerHost
  = String.fromEnvironment('CONVENIENT_TEST_MANAGER_HOST', defaultValue: '127.0.0.1');
  ``` to
  ```dart
  const String kConvenientTestManagerHost
  = String.fromEnvironment('CONVENIENT_TEST_MANAGER_HOST', defaultValue: '10.0.2.2');
```
And then recompiling the manager. I dont understand why this workaround has to be but for me this worked.
