### ISSUE TITLE
Type 'Plurality' not found

### ISSUE THREAD

**Issue by ahmdt** [fzyzcjy/flutter_convenient_test#363]
Anybody with this error here, when building?

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/convenient_test_dev-1.3.2/lib/src/utils/util.dart:12:25: Error: Type 'Plurality' not found.

**Comment by fzyzcjy** [comment]
Hi, which flutter version are you using? I guess it may be because flutter is too old/too new

**Comment by ahmdt** [comment]
its 3.13.3

**Comment by fzyzcjy** [comment]
Yes, Plurity is added to make it compatible with latest flutter (3.16). So if you are using flutter 3.13, need to use corresponding old convenient_test version.

**Comment by ahmdt** [comment]
works now. thank you!

**Comment by fzyzcjy** [comment]
You are welcome!
