### ISSUE TITLE
Unreadable text in the manager

### ISSUE THREAD

**Issue by Bazni** [fzyzcjy/flutter_convenient_test#365]
**Describe the bug**
Is it possible to change the background of the log?
Is it my log that is displayed in a weird way or a special config?

**To Reproduce**
1. Go to a failed test
2. Display the log

**Expected behavior**
Display a log readable, without the pale pink background.

**Screenshots**
![image](https://github.com/fzyzcjy/flutter_convenient_test/assets/25507395/03365da8-c62a-4fbf-a7d8-a08d39c853f0)

**Desktop (please complete the following information):**
 - OS: 14.2.1 (23C71)

**Comment by fzyzcjy** [comment]
Looks like this is fixed in https://github.com/fzyzcjy/flutter_convenient_test/pull/361. Could you please try master for manager?

**Comment by Bazni** [comment]
Perfect it's fixed. Thx

Btw you could increase the cocoa pods version in the gemfile of macOS to 1.14.3.

**Comment by fzyzcjy** [comment]
> Btw you could increase the cocoa pods version in the gemfile of macOS to 1.14.3.

May I know why? Is it because it causes some errors?

**Comment by fzyzcjy** [comment]
I see. Is it useable if the users have an old cocoapods? (I am not an expert of ios build tools) In libraries I always try to keep max compatibility when possible.

**Comment by Bazni** [comment]
Don't worry, keep it like this. In any case, users will have to change their cocoapods version in the gemfile.
If they don't have the version it will not compile whether it's the latest or an old one.

I'm not an expert too, maybe it is better to have an old version for old systems that can't get the last one (I don't know if it's possible)
