### ISSUE TITLE
pumpAndSettleWithRunAsync times out

### ISSUE THREAD

**Issue by Tomburgs** [fzyzcjy/flutter_convenient_test#369]
**Describe the bug**
Sometimes actions get stuck with a message saying _"pumpAndSettleWithRunAsync has been running for X cycles"_ repeatedly being logged to the console.

Interestingly, in some cases, the action does complete (can see it in the simulator), sometimes even with actions after it, however in logs and the test manager GUI it claims to still be stuck on a step already completed.

**To Reproduce**
I'm not sure how difficult it is to reproduce in other projects, but we have this simple sign up flow that fails practically every time at different points. Fails both on tap and text input steps.

```dart
tTestWidgets('register', (t) async {
  // Home screen
  await find.text('sign up').tap(settle: false);

  // Phone step
  await find.byKey(Key('phone-field')).enterTextWithoutReplace('${Random().nextInt(99999999 - 10000000 + 1) + 10000000}');
  await find.text('continue').tap();

  // Email step
  await find.byKey(Key('email-field')).enterTextWithoutReplace('e2e-test-${DateTime.now().millisecondsSinceEpoch}@email.com');
  await find.text('continue').tap();

  // Name step
  await find.byKey(Key('name-field')).enterTextWithoutReplace('Mr. Tester ${DateTime.now().millisecondsSinceEpoch}');
  await find.text('continue').tap();
});

```

**Expected behavior**
It should "just work".

**Screenshots**

In the screenshot below you can see one of these cases (it already clicked "continue" on the previous page to get to this page, yet according to the manager seemingly timed out when trying to click "continue").
![image](https://github.com/fzyzcjy/flutter_convenient_test/assets/23725326/58c75e2a-4c39-4c88-bb41-f83bd4b2c248)

**Desktop:**
 - OS: macOS 14.0 (23A344) — M1 MacBook Pro (if it matters)

**Smartphone:**
 - Device: iPhone 13 mini (**simulator**)
 - OS: 17.0

**Additional context**

This happens both with the #337 patch and without.

Here's the error log we got when it timed out trying to click the "continue" button (that it seemingly already clicked).
```
flutter: 2024-02-23T13:10:18.610409Z|debug|ConvenientTestInteraction|pumpAndSettleWithRunAsync has been running for 420 cycles
flutter: 2024-02-23T13:10:19.827150Z|debug|ConvenientTestInteraction|pumpAndSettleWithRunAsync has been running for 430 cycles
flutter: 2024-02-23T13:10:21.027654Z|debug|ConvenientTestInteraction|pumpAndSettleWithRunAsync has been running for 440 cycles
flutter: 2024-02-23T13:10:22.276517Z|debug|ConvenientTestInteraction|pumpAndSettleWithRunAsync has been running for 450 cycles
flutter: 2024-02-23T13:10:23.476898Z|debug|ConvenientTestInteraction|pumpAndSettleWithRunAsync has been running for 460 cycles
flutter: 2024-02-23T13:10:24.104295Z|info|LogHandle|🔵 (#2218346540010048, update) TAP doing pump, when widget with text "continue" pumpWithRunAsyncUntil timed out (startTime=WallAndFakeClock(wallClock: 2024-02-23 14:09:24.025708, fakeClock: 2024-02-23 14:09:24.025707), endTime=WallAndFakeClock(wallClock: 2024-02-23 14:10:24.025708, fakeClock: 2024-02-23 14:10:24.025707), now=WallAndFakeClock(wallClock: 2024-02-23 14:10:24.093327, fakeClock: 2024-02-23 14:10:24.093326), pumpCount=465) #0      ExtWidgetTesterPump.pumpWithRunAsyncUntil.<anonymous closure> (package:convenient_test_dev/src/functions/widget_tester.dart:132:11)
flutter: <asynchronous suspension>
flutter: #1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
flutter: <asynchronous suspension>
flutter: #2      ExtWidgetTesterPump.pumpAndSettleWithRunAsync (package:convenient_test_dev/src/functions/widget_tester.dart:92:7)
flutter: <asynchronous suspension>
flutter: #3      ExtWidgetTesterPump.pumpAndMaybeSettleWithRunAsync (package:convenient_test_dev/src/functions/widget_tester.dart:82:24)
flutter: <asynchronous suspension>
flutter: #4      TFinderCommand.act (package:convenient_test_dev/src/functions/find.dart:277:7)
flutter: <asynchronous suspension>
flutter: #5      main.<anonymous closure>.<anonymous closure> (file:///Users/....../app/integration_test/main_test.dart:23:9)
flutter: <asynchronous suspension>
flutter: #6      tTestWidgets.<anonymous closure>.<anonymous closure> (package:convenient_test_dev/src/functions/test_widgets.dart:41:7)
flutter: <asynchronous suspension>
flutter: #7      ConvenientTest.withActiveInstance (package:convenient_test_dev/src/functions/instance.dart:29:7)
flutter: <asynchronous suspension>
flutter: #8      tTestWidgets.<anonymous closure> (package:convenient_test_dev/src/functions/test_widgets.dart:26:23)
flutter: <asynchronous suspension>
flutter: #9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
flutter: <asynchronous suspension>
flutter: #10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1015:5)
flutter: <asynchronous suspension>
flutter: #11     TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:806:12)
flutter: <asynchronous suspension>
```

**Versions:**
```yaml
  convenient_test: ^1.3.3
  convenient_test_dev: ^1.3.3
```

**Comment by fzyzcjy** [comment]
> after looking into this more it seems that binding.hasScheduledFrame always returns true.

Hmm, maybe because there are some animations?

Just a guess: Is it because of cursor blinking, https://api.flutter.dev/flutter/widgets/EditableText/debugDeterministicCursor.html

> doesn't accept the settle argument, whereas their actual implementations do. is this overlooked or intentional?

If you can simply forward settle argument into the inner function, then usually it is just overlooked, feel free to PR! (the settle arg is added later, thus maybe not all outer wrapper functions added this)

**Comment by Tomburgs** [comment]
> Hmm, maybe because there are some animations?
>
> Just a guess: Is it because of cursor blinking, https://api.flutter.dev/flutter/widgets/EditableText/debugDeterministicCursor.html

thanks for the help, seems like the blinking cursor was exactly what was causing all the issues! disabled it and it works like a charm with no flakiness whatsoever.

> If you can simply forward settle argument into the inner function, then usually it is just overlooked, feel free to PR! (the settle arg is added later, thus maybe not all outer wrapper functions added this)

sweet, will look into this later! awesome work with the library by the way, in my opinion it's something that the flutter world desperately needed 🫶

**Comment by fzyzcjy** [comment]
You are welcome, and thank you as well!
