### ISSUE TITLE
Launch with Debug feature in VSCode

### ISSUE THREAD

**Issue by AngDrew** [fzyzcjy/flutter_convenient_test#376]
**Is your feature request related to a problem? Please describe.**
I'm frustrated with the terminal, because i can't filter things and the test just spammed with many things makes me can't read everything. I'd like to use Debug feature in VSCode to run the integration test.
when i tries to make one, it can't be done
```
    {
      "name": "Flutter Integration Test",
      "request": "launch",
      "type": "dart",
      "program": "integration_test/main_test.dart",
      "args": [
        "--flavor",
        "dev",
        "--host-vmservice-port",
        "9753",
        "--disable-service-auth-codes",
        "--dart-define",
        "CONVENIENT_TEST_MANAGER_HOST=10.0.2.2",
        "--dart-define",
        "CONVENIENT_TEST_APP_CODE_DIR=D:/projects/flutter-project/project_name",
        "--dart-define",
        "PERSISTENT_ARGUMENTS=clSs.clSp",
        "--dart-define",
        "TEST_ENTRY_POINT=onboarding"
      ]
    }
```
it says `Could not find an option named "host-vmservice-port".`
when i remove it, it says `No tests were found.` while exiting the app

**Describe the solution you'd like**
i'd like to run the test via vscode launch debug

**Describe alternatives you've considered**
currently i'm making bat file like this:
```
echo off
adb uninstall com.example.project_name.dev
flutter run ^
integration_test/main_test.dart ^
--flavor dev ^
--host-vmservice-port 9753 ^
--disable-service-auth-codes ^
--dart-define ^
CONVENIENT_TEST_MANAGER_HOST=10.0.2.2 ^
--dart-define ^
CONVENIENT_TEST_APP_CODE_DIR=D:/projects/flutter-project/project_name^

--dart-define PERSISTENT_ARGUMENTS=clSs.clSp ^
--dart-define TEST_ENTRY_POINT=onboarding
```

**Additional context**

**Comment by fzyzcjy** [comment]
Hi, firstly,

      "type": "dart",

I do not use vscode for this, so I wonder whether the type should be flutter?

**Comment by AngDrew** [comment]
sorry for the late reply, there's no option for flutter, there is just another framework
![image](https://github.com/fzyzcjy/flutter_convenient_test/assets/20359911/6e6078a0-65e5-4421-8fb0-d7a7bc465497)

**Comment by fzyzcjy** [comment]
> I'm frustrated with the terminal, because i can't filter things and the test just spammed with many things makes me can't read everything.

Btw, you can `your_command > a.log` or `your_command | tee a.log`, then look at the log files

As for the  `Could not find an option named "host-vmservice-port"` issue, I guess this is a general "how to specify flutter commands in VSCode" issue.

**Comment by AngDrew** [comment]
But `host-vmservice-port` works if I use the terminal. I'd like to keep this issue open. I've tried many ways to use the debugger but can't figure it out yet. Maybe someone will come here and help resolve this issue.

**Comment by fzyzcjy** [comment]
> But host-vmservice-port works if I use the terminal.

That's why I guess it may be a general flutter issue. If you can reproduce it using a blank Flutter project, maybe an issue can be created at official flutter repo / stackoverflow / etc to ask about this.
