### ISSUE TITLE
Simple step by step tutorial on how to get the manager and example tests setup & running

### ISSUE THREAD

**Issue by lunakoan** [fzyzcjy/flutter_convenient_test#384]
**Is your feature request related to a problem? Please describe.**
The readme does not mention the patch required to flutter test binding for tests to run and it also assumes a user knows how to navigate Github to get the build artefacts. It also mentions the example project, but there is no step-by-step tutorial on how to get this running alongside the manager.

**Describe the solution you'd like**
A simple step by step tutorial with screenshots on all the steps involved with getting the manager built/downloaded & running and the example tests running. Things I would also love to see documented are why and how to apply the patch from https://github.com/fzyzcjy/flutter_convenient_test/issues/337 and where to find the artefacts from the CI (screenshots on how to navigate the Github UI). Being able to follow this tutorial would give users more confidence that they know what they are doing and everything is set-up and working correctly 😄 

**Describe alternatives you've considered**
Update the description of https://github.com/fzyzcjy/flutter_convenient_test/issues/337 with an example of what the binding file looks like after the changes as a git-diff is confusing to read for someone who doesn't use this feature of git.

**Comment by lunakoan** [comment]
I am happy to PR this once I am sure I know how to apply the patch correctly and get all the example tests passing :)

**Comment by fzyzcjy** [comment]
Looks pretty reasonable and looking forward to your PR!
