### ISSUE TITLE
Release artefacts not published due to permissions error in action

### ISSUE THREAD

**Issue by lunakoan** [fzyzcjy/flutter_convenient_test#400]
**Describe the bug**
Release artefacts cannot be published due to a permissions error in the action

**To Reproduce**
1. Go to a release build
2. Click into a build step such as `build_manager_macos`
3. See `Add to release if tagged` step fails with error `Unexpected error fetching GitHub release for tag refs/tags/v1.5.0: HttpError: Resource not accessible by integration` like so https://github.com/fzyzcjy/flutter_convenient_test/actions/runs/9728179521/job/26848628632#step:12:11

**Expected behavior**
Build artefacts should be accessible on releases

**Screenshots**
![Screenshot 2024-07-03 at 4 22 24 PM](https://github.com/fzyzcjy/flutter_convenient_test/assets/119916943/c43afe63-a29c-4c68-a825-4bfffc575861)

**Additional context**
Suggested fix https://github.com/orgs/community/discussions/60820#discussioncomment-8342277

**Comment by fzyzcjy** [comment]
Close since https://github.com/fzyzcjy/flutter_convenient_test/pull/401
