### ISSUE TITLE
If I want to migrate from the integration_test API to flutter_convenient_test, what do I need to do?

### ISSUE THREAD

**Issue by zhanchen18** [fzyzcjy/flutter_convenient_test#404]
I was previously using integration_test and now want to try flutter_convenient_test. Will I need to make a lot of code changes? If the workload is too heavy, I might give up on using it.

**Comment by fzyzcjy** [comment]
IMHO no. Just look at the tutorials, it mimics the standard Flutter test a lot.

**Comment by zhanchen18** [comment]
> IMHO no. Just look at the tutorials, it mimics the standard Flutter test a lot.

I must use the API provided by flutter_convenient_test instead of the integration_test API, otherwise the test steps and screenshots will not be visible in the convenient_test_manager.

**Comment by fzyzcjy** [comment]
Oh if you mean this then yes. I meant the logic is almost the same (e.g. "find a widget and tap it")
