### ISSUE TITLE
I encountered this error message when testing on an Android device, but there are no issues when testing on the emulator.

### ISSUE THREAD

**Issue by zhanchen18** [fzyzcjy/flutter_convenient_test#405]
code: https://github.com/fzyzcjy/flutter_convenient_test/blob/master/packages/convenient_test/example/integration_test/main_test.dart

flutter run integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define "CONVENIENT_TEST_APP_CODE_DIR=$PWD"

run in Android Studio.

error message: Unhandled Exception: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 41632, details: null, rawResponse: null, trailers: {})

**Comment by zhanchen18** [comment]
My computer is set up with a local IP address, I should use --dart-define CONVENIENT_TEST_MANAGER_HOST=192.168.0.11 instead of --dart-define CONVENIENT_TEST_MANAGER_HOST=127.0.0.1

**Comment by fzyzcjy** [comment]
Yes, you need to specify the host that can be communicated. Does setting up the 192.168.x.x solve your problem?

**Comment by zhanchen18** [comment]
> Yes, you need to specify the host that can be communicated. Does setting up the 192.168.x.x solve your problem?

Yes,This method is helpful.
